[package]
name = "rizin-librz-sys"
version = "0.7.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
meson-next = "1.2.2"
bindgen = "0.69.4"
libc = "0.2.153"

[dependencies]
